# -*- coding: utf-8 -*-
"""VaR_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueDKdi8O4d75fKNr1_klCTnoevTRjs1X
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def VaR(r, confidence, principal=1):
    return principal * abs(np.percentile(r, (1 - confidence) * 100))

def percent_var(r, confidence):
    plt.hist(r, bins=50, alpha=0.75)
    plt.show()
    return abs(np.percentile(r, (1 - confidence) * 100))

r = np.random.normal(0.05, 0.03, 1000000)
probability2SD = norm.cdf(2)

my_confidence = probability2SD
my_percent_var = percent_var(r, my_confidence)
print(np.round(my_percent_var, 2) == 0.01)