# -*- coding: utf-8 -*-
"""YFinance_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBY8fS5k9ufque4Bu4VfpMLHkiQ1RFAk
"""

import pandas as pd

import numpy as np

import yfinance as yf

import matplotlib.pyplot as plt

def get_stock_data(symbol):
  stock_data = yf.download(symbol, auto_adjust=False)
  return stock_data

def get_returns(YahooData):
    pricevec = YahooData['Adj Close'].to_numpy()
    ratiovec = pricevec[1:] / pricevec[:-1]
    returns = ratiovec - 1
    return returns

symbol = 'GS'
df = get_stock_data(symbol)
returns = get_returns(df)
print(returns)

print("\nDataFrame head:\n", df.head())
print("\nDataFrame tail:\n", df.tail())


df['Adj Close'].plot(figsize=(10, 6), title=f"{symbol} Adj Close Price")
plt.xlabel("Date")
plt.ylabel("Price (USD)")
plt.show()

d = { 'Open': [100, 102, 101, 103],

'High': [105, 104, 103, 105],

'Low': [98, 100, 99, 101],

'Close': [101, 103, 102, 104],

'Adj Close': [101, 103, 102, 104],

'Volume': [1000, 1200, 900, 1100]}



index = pd.to_datetime(['2023-10-26', '2023-10-27', '2023-10-28', '2023-10-29'])

tempdata = pd.DataFrame(d, index=index)

np.isclose(returns[0], 0.01980198, atol=0.01)

np.isclose(returns[1], -0.00970874, atol=0.01)

np.isclose(returns[2], 0.01960784, atol=0.01)

my_returns = get_returns(tempdata)
print(my_returns)